---
# tasks file for ansible-nomad-server

- name: Check requirements
  include: assets.yml

- name: Include OS variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include nomad user and group creation tasks
  include: user_group.yml

- name: Include requirements installation tasks
  include: requirements.yml

- name: Include nomad installation tasks
  include: install.yml

- name: Include nomad configurations tasks
  include: configure.yml