---
- name: Ensure required OS packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nomad_os_packages }}"

- name: Ensure bin, data and config directories have been created
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0755
  with_items:
    - "{{ nomad_data_dir }}"
    - "{{ nomad_bin_dir }}"
    - "{{ nomad_config_dir }}"
    - "{{ nomad_run_dir }}"

- name: Extract systemd version
  shell: |
    set -o pipefail
    systemctl --version systemd | head -n 1 | cut -d' ' -f2
  args:
    executable: /bin/bash
  changed_when: false
  check_mode: false
  register: systemd_version
  when:
    - ansible_service_mgr == "systemd"
    - not ansible_os_family == "FreeBSD"
    - not ansible_os_family == "Solaris"