---
# File user_group.yml : used to create nomad user and group on the server

- name: Ensure Nomad group has been created
  group:
    name: "{{ nomad_group }}"
    state: present

- name: Ensure Nomad user has been created
  user:
    name: "{{ nomad_user }}"
    comment: "Nomad user"
    group: "{{ nomad_group }}"
    system: yes

- name: Ensure Nomad user has been created and added to docker group
  user:
    name: "{{ nomad_user }}"
    comment: "Nomad user"
    group: "{{ nomad_group }}"
    groups: "{{ docker_group }}"
    system: yes
  when: nomad_docker_enabled == true and nomad_node_role == "client"
